spring:
  application:
    name: rest-call-scheduled

cron:
  job:
    schedule: "7 7 * * * *" #Every minute
    url: "https://eggdrop.pcfbeta.io/events/4"

logging:
  level:
    io.pivotal.example: DEBUG
