spring:
  application:
    name: rest-call-scheduled

cron:
  job:
    schedule: "0 * * * * *" #Every minute
    url: "https://eggdrop.cfapps.io/events/1"

logging:
  level:
    io.pivotal.example: DEBUG
